name: "Build Development Docker Image into DockerHub"

# trigger the workflow when a push is committed to the develop branch
on:
  push:
    branches:
      - develop

# environment variables used for the respective instance (edit as needed)
env:
  # docker variables
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ github.head_ref }}
  # dockerhub credentials
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    name: Build and Push Development Docker Image into DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest