name: "Build Development Docker Image into Artifact Registry"

# trigger the workflow when a push is committed to the develop branch
on:
  push:
    branches:
      - develop

jobs:
  # builds the docker image via cloud build
  build:
    name: Build Development Docker Image into Artifact Registry
    uses: Datawheel/.github/.github/workflows/gcp-build-to-registry.yml@main
    with:
      IMAGE_TAG: ${{ github.sha }}
    secrets: inherit