name: "Build Production Docker Image into Artifact Registry"

# trigger the workflow when a release is published
on:
  release:
    types: [published]

jobs:
  # get release version number
  release:
    name: Get release version number
    steps:
      - name: Get release version number
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

  # builds the docker image via cloud build
  build:
    name: Build Production Docker Image into Artifact Registry
    uses: Datawheel/.github/.github/workflows/gcp-build-to-registry.yaml@main
    needs: release
    with:
      IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      IMAGE_ENVIRONMENT: 'prod'
    secrets: inherit